In [1]:
import pandas as pd

In [2]:
customers=pd.read_csv(r"C:\Users\ashur\Desktop\Project\olist_customers_dataset.csv")
orders=pd.read_csv(r"C:\Users\ashur\Desktop\Project\olist_orders_dataset.csv")
order_items=pd.read_csv(r"C:\Users\ashur\Desktop\Project\olist_order_items_dataset.csv")
products=pd.read_csv(r"C:\Users\ashur\Desktop\Project\olist_products_dataset.csv")
payments=pd.read_csv(r"C:\Users\ashur\Desktop\Project\olist_order_payments_dataset.csv")
reviews=pd.read_csv(r"C:\Users\ashur\Desktop\Project\olist_order_reviews_dataset.csv")
sellers=pd.read_csv(r"C:\Users\ashur\Desktop\Project\olist_sellers_dataset.csv")
category=pd.read_csv(r"C:\Users\ashur\Desktop\Project\product_category_name_translation.csv")
geolocation=pd.read_csv(r"C:\Users\ashur\Desktop\Project\olist_geolocation_dataset.csv")

# Each Dataset Overview

#### Customers Dataset

In [9]:
customers.head(10)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP
5,879864dab9bc3047522c92c82e1212b8,4c93744516667ad3b8f1fb645a3116a4,89254,jaragua do sul,SC
6,fd826e7cf63160e536e0908c76c3f441,addec96d2e059c80c30fe6871d30d177,4534,sao paulo,SP
7,5e274e7a0c3809e14aba7ad5aae0d407,57b2a98a409812fe9618067b6b8ebe4f,35182,timoteo,MG
8,5adf08e34b2e993982a47070956c5c65,1175e95fb47ddff9de6b2b06188f7e0d,81560,curitiba,PR
9,4b7139f34592b3a31687243a302fa75b,9afe194fb833f79e300e37e580171f22,30575,belo horizonte,MG

In [11]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 3.8 MB

In [13]:
customers.shape

(99441, 5)

In [15]:
customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [17]:
customers.duplicated().sum()

np.int64(0)

### Orders Dataset

In [20]:
orders.head(10)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00
5,a4591c265e18cb1dcee52889e2d8acc3,503740e9ca751ccdda7ba28e9ab8f608,delivered,2017-07-09 21:57:05,2017-07-09 22:10:13,2017-07-11 14:58:04,2017-07-26 10:57:55,2017-08-01 00:00:00
6,136cce7faa42fdb2cefd53fdc79a6098,ed0271e0b7da060a393796590e7b737a,invoiced,2017-04-11 12:22:08,2017-04-13 13:25:17,NaN,NaN,2017-05-09 00:00:00
7,6514b8ad8028c9f2cc2374ded245783f,9bdf08b4b3b52b5526ff42d37d47f222,delivered,2017-05-16 13:10:30,2017-05-16 13:22:11,2017-05-22 10:07:46,2017-05-26 12:55:51,2017-06-07 00:00:00
8,76c6e866289321a7c93b82b54852dc33,f54a9f0e6b351c431402b8461ea51999,delivered,2017-01-23 18:29:09,2017-01-25 02:50:47,2017-01-26 14:16:31,2017-02-02 14:08:10,2017-03-06 00:00:00
9,e69bfb5eb88e0ed6a785585b27e16dbf,31ad1d1b63eb9962463f764d4e6e0c9d,delivered,2017-07-29 11:55:02,2017-07-29 12:05:32,2017-08-10 19:45:24,2017-08-16 17:14:30,2017-08-23 00:00:00

In [21]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB

In [23]:
orders.shape

(99441, 8)

In [24]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [25]:
orders.duplicated().sum()

np.int64(0)

### Order Item Dataset

In [26]:
order_items.head(10)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14
5,00048cc3ae777c65dbb7d2a0634bc1ea,1,ef92defde845ab8450f9d70c526ef70f,6426d21aca402a131fc0a5d0960a3c90,2017-05-23 03:55:27,21.90,12.69
6,00054e8431b9d7675808bcb819fb4a32,1,8d4f2bb7e93e6710a28f34fa83ee7d28,7040e82f899a04d1b434b795a43b4617,2017-12-14 12:10:31,19.90,11.85
7,000576fe39319847cbb9d288c5617fa6,1,557d850972a7d6f792fd18ae1400d9b6,5996cddab893a4652a15592fb58ab8db,2018-07-10 12:30:45,810.00,70.75
8,0005a1a1728c9d785b8e2b08b904576c,1,310ae3c140ff94b03219ad0adc3c778f,a416b6a846a11724393025641d4edd5e,2018-03-26 18:31:29,145.95,11.65
9,0005f50442cb953dcd1d21e1fb923495,1,4535b0e1091c278dfd193e5a1d63b39f,ba143b05f0110f0dc71ad71b4466ce92,2018-07-06 14:10:56,53.99,11.40

In [27]:
order_items.info()

<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  str
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 6.0 MB

In [28]:
order_items.shape

(112650, 7)

In [29]:
order_items.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [30]:
order_items.duplicated().sum()

np.int64(0)

### Product Dataset

In [31]:
products.head(10)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0
5,41d3672d4792049fa1779bb35283ed13,instrumentos_musicais,60.0,745.0,1.0,200.0,38.0,5.0,11.0
6,732bd381ad09e530fe0a5f457d81becb,cool_stuff,56.0,1272.0,4.0,18350.0,70.0,24.0,44.0
7,2548af3e6e77a690cf3eb6368e9ab61e,moveis_decoracao,56.0,184.0,2.0,900.0,40.0,8.0,40.0
8,37cc742be07708b53a98702e77a21a02,eletrodomesticos,57.0,163.0,1.0,400.0,27.0,13.0,17.0
9,8c92109888e8cdf9d66dc7e463025574,brinquedos,36.0,1156.0,1.0,600.0,17.0,10.0,12.0

In [32]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       32341 non-null  str
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), str(2)
memory usage: 2.3 MB

In [33]:
products.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [34]:
products.shape

(32951, 9)

In [35]:
products.duplicated().sum()

np.int64(0)

### Payment Dataset

In [36]:
payments.head(10)

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45
5,298fcdf1f73eb413e4d26d01b25bc1cd,1,credit_card,2,96.12
6,771ee386b001f06208a7419e4fc1bbd7,1,credit_card,1,81.16
7,3d7239c394a212faae122962df514ac7,1,credit_card,3,51.84
8,1f78449c87a54faf9e96e88ba1491fa9,1,credit_card,6,341.09
9,0573b5e23cbd798006520e1d5b4c6714,1,boleto,1,51.95

In [37]:
payments.info()

<class 'pandas.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  str
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  str
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 4.0 MB

In [38]:
payments.shape

(103886, 5)

In [39]:
payments.isnull().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [40]:
payments.duplicated().sum()

np.int64(0)

### Review Dataset

In [41]:
reviews.head(10)

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53
5,15197aa66ff4d0650b5434f1b46cda19,b18dcdf73be66366873cd26c5724d1dc,1,NaN,NaN,2018-04-13 00:00:00,2018-04-16 00:39:37
6,07f9bee5d1b850860defd761afa7ff16,e48aa0d2dcec3a2e87348811bcfdf22b,5,NaN,NaN,2017-07-16 00:00:00,2017-07-18 19:30:34
7,7c6400515c67679fbee952a7525281ef,c31a859e34e3adac22f376954e19b39d,5,NaN,NaN,2018-08-14 00:00:00,2018-08-14 21:36:06
8,a3f6f7f6f433de0aefbb97da197c554c,9c214ac970e84273583ab523dfafd09b,5,NaN,NaN,2017-05-17 00:00:00,2017-05-18 12:05:37
9,8670d52e15e00043ae7de4c01cc2fe06,b9bf720beb4ab3728760088589c62129,4,recomendo,aparelho eficiente. no site a marca do aparelh...,2018-05-22 00:00:00,2018-05-23 16:45:47

In [42]:
reviews.info()

<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  str
 1   order_id                 99224 non-null  str
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  str
 4   review_comment_message   40977 non-null  str
 5   review_creation_date     99224 non-null  str
 6   review_answer_timestamp  99224 non-null  str
dtypes: int64(1), str(6)
memory usage: 5.3 MB

In [43]:
reviews.shape

(99224, 7)

In [44]:
reviews.isnull().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [45]:
reviews.duplicated().sum()

np.int64(0)

### Seller Dataset

In [46]:
sellers.head(10)

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP
5,c240c4061717ac1806ae6ee72be3533b,20920,rio de janeiro,RJ
6,e49c26c3edfa46d227d5121a6b6e4d37,55325,brejao,PE
7,1b938a7ec6ac5061a66a3766e0e75f90,16304,penapolis,SP
8,768a86e36ad6aae3d03ee3c6433d61df,1529,sao paulo,SP
9,ccc4bbb5f32a6ab2b7066a4130f114e3,80310,curitiba,PR

In [47]:
sellers.info()

<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   str
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   str
 3   seller_state            3095 non-null   str
dtypes: int64(1), str(3)
memory usage: 96.8 KB

In [55]:
sellers.shape

(3095, 4)

In [50]:
sellers.isnull().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [51]:
sellers.duplicated().sum()

np.int64(0)

### category Dataset

In [52]:
category.head(10)

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor
5           esporte_lazer                sports_leisure
6              perfumaria                     perfumery
7   utilidades_domesticas                    housewares
8               telefonia                     telephony
9      relogios_presentes                 watches_gifts

In [53]:
category.info()

<class 'pandas.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     str
 1   product_category_name_english  71 non-null     str
dtypes: str(2)
memory usage: 1.2 KB

In [54]:
category.shape

(71, 2)

In [55]:
category.isnull().sum()

product_category_name            0
product_category_name_english    0
dtype: int64

In [56]:
category.duplicated().sum()

np.int64(0)

### Geolocation Dataset

In [57]:
geolocation.head(10)

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP
5,1012,-23.547762,-46.635361,são paulo,SP
6,1047,-23.546273,-46.641225,sao paulo,SP
7,1013,-23.546923,-46.634264,sao paulo,SP
8,1029,-23.543769,-46.634278,sao paulo,SP
9,1011,-23.547640,-46.636032,sao paulo,SP

In [58]:
geolocation.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  str
 4   geolocation_state            1000163 non-null  str
dtypes: float64(2), int64(1), str(2)
memory usage: 38.2 MB

In [59]:
geolocation.shape

(1000163, 5)

In [60]:
geolocation.isnull().sum()

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [61]:
geolocation.duplicated().sum()

np.int64(261831)

# Data Cleaning Strategy

In [ ]:
Before Cleaning the Dataset,Each table was inspected for missing values,duplicates and data quality issues.
1.Customers  ==> No missing values or duplicates,No cleaning required.
2.orders     ==> missing values were found in date columns,these missing values are expected because some orders were cancelled or were never delivered 
                 therefore they will not be removed for delivery related analysis,only delivered orders will be considered.
3.order items==> No missing values or duplicates,No cleaning required.
4.products   ==> A total of 610 missing values belong to the same set of products so they will not be removed at this stage. The decision will be based on the
                 analysis requirements.
5.reviews    ==> Missing Values in title and message are expected because many customers provide only rating ,These columns will not be filled or removed unless
                 text analysis is performed.
6.Geolocation ==> Duplicate records are expected because the same ZIP code or location can appear multiple times deduplication will only be performed when
                  if required for geolocation analysis.

In [ ]:
""" Before EDA ,first convert all Date columns into Datetime format."""

In [3]:
orders["order_purchase_timestamp"]=pd.to_datetime(orders["order_purchase_timestamp"])
orders["order_approved_at"]=pd.to_datetime(orders["order_approved_at"])
orders["order_delivered_carrier_date"]=pd.to_datetime(orders["order_delivered_carrier_date"])
orders["order_delivered_customer_date"]=pd.to_datetime(orders["order_delivered_customer_date"])
orders["order_estimated_delivery_date"]=pd.to_datetime(orders["order_estimated_delivery_date"])
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  datetime64[us]
 4   order_approved_at              99281 non-null  datetime64[us]
 5   order_delivered_carrier_date   97658 non-null  datetime64[us]
 6   order_delivered_customer_date  96476 non-null  datetime64[us]
 7   order_estimated_delivery_date  99441 non-null  datetime64[us]
dtypes: datetime64[us](5), str(3)
memory usage: 6.1 MB

# EDA

In [24]:
# 1.Total orders ??
total_orders=orders["order_id"].nunique()
print(total_orders)

99441

In [ ]:
""" Business Insight """
The dataset contains 99441 unique customer orders indicating a large scale e-commerce bussiness with sufficient 
data for meaningful sales and customer analysis.

In [25]:
# 2.Order status distribution.
orders.order_status.value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [ ]:
""" Business Insight """
1. Around 97% orders successfully delivered.
2. cancelled and unavailable orders are very less in numbers.
3. some orders are in processing or shipping stage.

In [36]:
# 3.Monthly Order Trend
orders["Year_Month"]=orders["order_purchase_timestamp"].dt.to_period("M")
monthly_orders=orders.groupby("Year_Month")["order_id"].count()
monthly_orders

Year_Month
2016-09       4
2016-10     324
2016-12       1
2017-01     800
2017-02    1780
2017-03    2682
2017-04    2404
2017-05    3700
2017-06    3245
2017-07    4026
2017-08    4331
2017-09    4285
2017-10    4631
2017-11    7544
2017-12    5673
2018-01    7269
2018-02    6728
2018-03    7211
2018-04    6939
2018-05    6873
2018-06    6167
2018-07    6292
2018-08    6512
2018-09      16
2018-10       4
Freq: M, Name: order_id, dtype: int64

In [31]:
# 4.Total Revenue
revenue_df=orders.merge(order_items,on="order_id")
Total_revenue=revenue_df["price"].sum()
print(f"Total_revenue:{Total_revenue:,.2f}")

Total_revenue:13,591,643.70

In [37]:
# 5.Monthly Revenue Trend.
Monthly_Revenue=revenue_df.groupby("Year_Month")["price"].sum()
Monthly_Revenue

Year_Month
2016-09        267.36
2016-10      49507.66
2016-12         10.90
2017-01     120312.87
2017-02     247303.02
2017-03     374344.30
2017-04     359927.23
2017-05     506071.14
2017-06     433038.60
2017-07     498031.48
2017-08     573971.68
2017-09     624401.69
2017-10     664219.43
2017-11    1010271.37
2017-12     743914.17
2018-01     950030.36
2018-02     844178.71
2018-03     983213.44
2018-04     996647.75
2018-05     996517.68
2018-06     865124.31
2018-07     895507.22
2018-08     854686.33
2018-09        145.00
Freq: M, Name: price, dtype: float64

In [45]:
# 6. Top 10 Product Categories by revenue.
Category_revenue=order_items.merge(products[["product_id","product_category_name"]],on="product_id",how="left")
Category_revenue=Category_revenue.merge(category,on="product_category_name")
Category_revenue.groupby("product_category_name_english")["price"].sum().sort_values(ascending=False).head(10)

product_category_name_english
health_beauty            1258681.34
watches_gifts            1205005.68
bed_bath_table           1036988.68
sports_leisure            988048.97
computers_accessories     911954.32
furniture_decor           729762.49
cool_stuff                635290.85
housewares                632248.66
auto                      592720.11
garden_tools              485256.46
Name: price, dtype: float64

In [56]:
# 7.Top 10 cities by Number of Orders
city_orders=orders.merge(customers[["customer_id","customer_city"]],on="customer_id",how="left")
city_orders.groupby("customer_city")["order_id"].count().sort_values(ascending=False).head(10)

customer_city
sao paulo                15540
rio de janeiro            6882
belo horizonte            2773
brasilia                  2131
curitiba                  1521
campinas                  1444
porto alegre              1379
salvador                  1245
guarulhos                 1189
sao bernardo do campo      938
Name: order_id, dtype: int64

In [58]:
# 8.Top 10 states by Number of Orders
state_orders=orders.merge(customers[["customer_id","customer_state"]],on="customer_id",how="left")
state_orders.groupby("customer_state")["order_id"].count().sort_values(ascending=False).head(10)

customer_state
SP    41746
RJ    12852
MG    11635
RS     5466
PR     5045
SC     3637
BA     3380
DF     2140
ES     2033
GO     2020
Name: order_id, dtype: int64

In [60]:
# 9.Payment Method Distribution
payments.payment_type.value_counts()

payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

In [66]:
payments.payment_type.value_counts(normalize=True).mul(100).round(2)

payment_type
credit_card    73.92
boleto         19.04
voucher         5.56
debit_card      1.47
not_defined     0.00
Name: proportion, dtype: float64

In [15]:
# 10.Average Order Value(AOV)
total_rev=orders.merge(order_items,on="order_id")
a=total_rev.price.sum()
b=total_rev.order_id.nunique()
AOV=a/b
print(f"AOV:R${AOV:,.2f}")

AOV:R$137.75

In [25]:
# 11.Average Delivery Time
orders["Delivery Days"]=orders["order_delivered_customer_date"]-orders["order_purchase_timestamp"]
orders["Delivery Days"].mean()

Timedelta('12 days 13:24:31.879068')

In [31]:
# 12.Order cancellation rate
a=(orders["order_status"]=="canceled").sum()
b=orders.order_id.nunique()
Cancellation_Rate=(a/b)*100
print(f"Cancellation Rate:{Cancellation_Rate:.2f}%")

Cancellation Rate:0.63%

In [40]:
# 13.Average Review Rate
reviews["review_score"].mean()

np.float64(4.08642062404257)

In [42]:
# 14.Review Score distribution
reviews["review_score"].value_counts().sort_index()

review_score
1    11424
2     3151
3     8179
4    19142
5    57328
Name: count, dtype: int64

In [49]:
# 15.Top 10 Sellers by Revenue
seller_revenue=order_items.groupby("seller_id")["price"].sum()
seller_revenue.sort_values(ascending=False).head(10)

seller_id
4869f7a5dfa277a7dca6462dcf3b52b2    229472.63
53243585a1d6dc2643021fd1853d8905    222776.05
4a3ca9315b744ce9f8e9374361493884    200472.92
fa1c13f2614d7b5c4749cbc52fecda94    194042.03
7c67e1448b00f6e969d365cea6b010ab    187923.89
7e93a43ef30c4f03f38b393420bc753a    176431.87
da8622b14eb17ae2831f4ac5b9dab84a    160236.57
7a67c85e85bb2ce8582c35f2203ad736    141745.53
1025f0e2d44d7041d6cf58b6550e0bfa    138968.55
955fee9216a65b617aa5c0531780ce60    135171.70
Name: price, dtype: float64

In [54]:
# 16.Top 10 Products By Revenue
product_revenue=order_items.groupby("product_id")["price"].sum()
product_revenue.sort_values(ascending=False).head(10)

product_id
bb50f2e236e5eea0100680137654686c    63885.00
6cdd53843498f92890544667809f1595    54730.20
d6160fb7873f184099d9bc95e30376af    48899.34
d1c427060a0f73f6b889a5c7c61f2ac4    47214.51
99a4788cb24856965c36a24e339b6058    43025.56
3dd2a17168ec895c781a9191c1e95ad7    41082.60
25c38557cf793876c5abdd5931f922db    38907.32
5f504b3a1c75b73d6151be81eb05bdc9    37733.90
53b36df67ebb7c41585e8d54d6772e08    37683.42
aca2eb7d00ea1a7b8ebd4e68314663af    37608.90
Name: price, dtype: float64

In [61]:
# 17.Order Items Per Order
Items_per_order=order_items.groupby("order_id")["order_item_id"].count()
Items_per_order.mean()
# relatively low basket size

np.float64(1.1417306873695092)

In [68]:
# 18.Top 10 City by revenue.
City_revenue=orders.merge(customers,on="customer_id").merge(order_items,on="order_id")
City_revenue.groupby("customer_city")["price"].sum().sort_values(ascending=False).head(10)

customer_city
sao paulo         1914924.54
rio de janeiro     992538.86
belo horizonte     355611.13
brasilia           301920.25
curitiba           211738.06
porto alegre       190562.08
campinas           187844.53
salvador           181104.42
guarulhos          144268.39
niteroi            117907.12
Name: price, dtype: float64

In [79]:
# 19.Top 10 Product Categories by Number of Orders
product_category=order_items.merge(products[["product_id","product_category_name"]],on="product_id").merge(category,on="product_category_name")
product_category.groupby("product_category_name_english")["order_id"].count().sort_values(ascending=False).head(10)

product_category_name_english
bed_bath_table           11115
health_beauty             9670
sports_leisure            8641
furniture_decor           8334
computers_accessories     7827
housewares                6964
watches_gifts             5991
telephony                 4545
garden_tools              4347
auto                      4235
Name: order_id, dtype: int64

In [83]:
# 20.Top 10 Sellers by number of Orders
order_items.groupby("seller_id")["order_id"].count().sort_values(ascending=False).head(10)

seller_id
6560211a19b47992c3666cc44a7e94c0    2033
4a3ca9315b744ce9f8e9374361493884    1987
1f50f920176fa81dab994f9023523100    1931
cc419e0650a3c5ba77189a1882b7556a    1775
da8622b14eb17ae2831f4ac5b9dab84a    1551
955fee9216a65b617aa5c0531780ce60    1499
1025f0e2d44d7041d6cf58b6550e0bfa    1428
7c67e1448b00f6e969d365cea6b010ab    1364
ea8482cd71df3c1969d7b9473ff13abc    1203
7a67c85e85bb2ce8582c35f2203ad736    1171
Name: order_id, dtype: int64

In [24]:
# 21.Top 10 seller by Average order value
total_sales=order_items.groupby("seller_id")["price"].sum()
total_orders=order_items.groupby("seller_id")["order_id"].nunique()
seller_aov=pd.DataFrame({"Total_Sales":total_sales,"Total_Orders":total_orders})
seller_aov["AOV"]=seller_aov["Total_Sales"]/seller_aov["Total_Orders"]
top_10=seller_aov.sort_values("AOV",ascending=False).head(10)
top_10

                                  Total_Sales  Total_Orders          AOV
seller_id
80ceebb4ee9b31afb6c6a916a574a1e2      6729.00             1  6729.000000
ee27a8f15b1dded4d213a468ba4eb391      6499.00             1  6499.000000
b37c4c02bda3161a7546a4e6d222d5b2     24075.00             4  6018.750000
585175ec331ea177fa47199e39a6170a      3549.00             1  3549.000000
abe021b01ba992245271b9aa422032df      6720.00             2  3360.000000
a00824eb9093d40e589b940ec45c4eb0      9399.97             3  3133.323333
e2a1ac9bf33e5549a2a4f834e70df2f8     14999.45             5  2999.890000
e908c0f3646e8b60375734a350d95d71      2951.00             1  2951.000000
d63c73efd41eb002280e7ec831424edb      5598.00             2  2799.000000
1444c08e64d55fb3c25f0f09c07ffcf2      2749.00             1  2749.000000

### Customer & Order Analysis

In [28]:
# 22.Top 10 Customer by revenue.
Customer_revenue=orders.merge(order_items[["order_id","price"]],on="order_id")
Customer_revenue.groupby("customer_id")["price"].sum().sort_values(ascending=False).head(10)

customer_id
1617b1357756262bfa56ab541c47bc16    13440.0
ec5b2ba62e574342386871631fafd3fc     7160.0
c6e2731c5b391845f6800c97401a43a9     6735.0
f48d464a0baaea338cb25f816991ab1f     6729.0
3fd6777bbce08a352fddd04e4a7cc8f6     6499.0
05455dfa7cd02f13d132aa7a6a9729c6     5934.6
df55c14d1476a9a3467f131269c2477f     4799.0
24bbf5fd2f2e1b359ee7de94defc4a15     4690.0
e0a2412720e9ea4f26c1ac985f6a7358     4599.9
3d979689f636322c62418b6346b1c6d2     4590.0
Name: price, dtype: float64

In [31]:
# 23.Top 10 Customer by Number of Orders [on customer_id basis].
orders.groupby("customer_id")["order_id"].count().sort_values(ascending=False).head(10)

customer_id
00012a2ce6f8dcda20d059ce98491703    1
000161a058600d5901f007fab4c27140    1
0001fd6190edaaf884bcaf3d49edf079    1
0002414f95344307404f0ace7a26f1d5    1
000379cdec625522490c315e70c7a9fb    1
0004164d20a9e969af783496f3408652    1
000419c5494106c306a97b5635748086    1
00046a560d407e99b969756e0b10f282    1
00050bf6e01e69d5c0fd612f1bcfb69c    1
000598caf2ef4117407665ac33275130    1
Name: order_id, dtype: int64

In [34]:
# 23.Top 10 Customer by Number of Orders
a=customers.merge(orders,on="customer_id")
a.groupby("customer_unique_id")["order_id"].count().sort_values(ascending=False).head(10)

customer_unique_id
8d50f5eadf50201ccdcedfb9e2ac8455    17
3e43e6105506432c953e165fb2acf44c     9
1b6c7548a2a1f9037c1fd3ddfed95f33     7
6469f99c1f9dfae7733b25662e7f1782     7
ca77025e7201e3b30c44b472ff346268     7
47c1a3033b8b77b3ab6e109eb4d5fdf3     6
12f5d6e1cbf93dafd9dcc19095df0b3d     6
63cfc61cee11cbe306bff5857d00bfe4     6
dc813062e0fc23409cd255f7f53c7074     6
de34b16117594161a6a89c50b289d35a     6
Name: order_id, dtype: int64

In [36]:
# 24.Average order per customer.
a=customers.merge(orders,on="customer_id")
a.groupby("customer_unique_id")["order_id"].count().mean()

np.float64(1.0348089410589412)

In [39]:
# 25.Repeat customers
a=customers.merge(orders,on="customer_id")
orders_per_customer=a.groupby("customer_unique_id")["order_id"].count()
repeat_customer=orders_per_customer[orders_per_customer>1]
repeat_customer.sort_values(ascending=False).head(10)

# 23 can also be used for this repeat customer insight.

customer_unique_id
8d50f5eadf50201ccdcedfb9e2ac8455    17
3e43e6105506432c953e165fb2acf44c     9
1b6c7548a2a1f9037c1fd3ddfed95f33     7
6469f99c1f9dfae7733b25662e7f1782     7
ca77025e7201e3b30c44b472ff346268     7
63cfc61cee11cbe306bff5857d00bfe4     6
47c1a3033b8b77b3ab6e109eb4d5fdf3     6
12f5d6e1cbf93dafd9dcc19095df0b3d     6
de34b16117594161a6a89c50b289d35a     6
dc813062e0fc23409cd255f7f53c7074     6
Name: order_id, dtype: int64

### Seller Analysis

In [42]:
# 26.Top 10 Sellers by Average Product price
order_items.groupby("seller_id")["price"].mean().sort_values(ascending=False).head(10)

seller_id
80ceebb4ee9b31afb6c6a916a574a1e2    6729.000000
ee27a8f15b1dded4d213a468ba4eb391    6499.000000
585175ec331ea177fa47199e39a6170a    3549.000000
abe021b01ba992245271b9aa422032df    3360.000000
a00824eb9093d40e589b940ec45c4eb0    3133.323333
e2a1ac9bf33e5549a2a4f834e70df2f8    2999.890000
e908c0f3646e8b60375734a350d95d71    2951.000000
d63c73efd41eb002280e7ec831424edb    2799.000000
1444c08e64d55fb3c25f0f09c07ffcf2    2749.000000
039e6ad9dae79614493083e241147386    2585.000000
Name: price, dtype: float64

In [43]:
# 27.Top 10 sellers by Total Items Sold.
order_items.groupby("seller_id")["order_id"].count().sort_values(ascending=False).head(10)

seller_id
6560211a19b47992c3666cc44a7e94c0    2033
4a3ca9315b744ce9f8e9374361493884    1987
1f50f920176fa81dab994f9023523100    1931
cc419e0650a3c5ba77189a1882b7556a    1775
da8622b14eb17ae2831f4ac5b9dab84a    1551
955fee9216a65b617aa5c0531780ce60    1499
1025f0e2d44d7041d6cf58b6550e0bfa    1428
7c67e1448b00f6e969d365cea6b010ab    1364
ea8482cd71df3c1969d7b9473ff13abc    1203
7a67c85e85bb2ce8582c35f2203ad736    1171
Name: order_id, dtype: int64

In [50]:
# 28.Sellers with Highest Average Review Score.
Review_Score=order_items.merge(reviews[["order_id","review_score"]],on="order_id")
Review_Score.groupby("seller_id")["review_score"].mean().sort_values(ascending=False).head(20)

seller_id
feb793c88d836c3a75efa4b5a3465d70    5.0
e59e575a175fadcadf8479e191770425    5.0
e595809a6c31ec4314fd06ef198c244d    5.0
e560e4022d8f7aebf155db95946c5c0f    5.0
e5545d4d4473876ea78c5bcebca365c3    5.0
392f7f2c797e4dc077e4311bde2ab8ce    5.0
333c4210e76a1aa2ab817b99437e3ff1    5.0
32f83ffe11cd40f7adcf4eef171f52d9    5.0
32e5635e63cb374eb63afdd242fb6134    5.0
38f276ca6e7cc95a6d1bb55ac9e5550f    5.0
389e45560e33d2d0747f949dcddbc08e    5.0
39a5005f2605cbdb4f9ac14485cabfd1    5.0
398cb257329ef7af7f1943a8974a3cbc    5.0
a56a8043ebf66e42119618fb8cf232c6    5.0
b00af24704019bd2e1b335e70ad11f7c    5.0
aec99834ab5d38ead22766ada8497e87    5.0
ae9690c6e8fee182c28c9ff8e11ca52c    5.0
ae45ad30c2d2e5913094769690a239d2    5.0
a70e9066dbfd10b6b97a3f54a1356762    5.0
05730013efda596306417c3b09302475    5.0
Name: review_score, dtype: float64

### Product & Category Analysis

In [3]:
# 29.Top 10 Product Categories by Average Product Price.
a=order_items.merge(products[["product_id","product_category_name"]],on="product_id").merge(category,on="product_category_name")
a.groupby("product_category_name_english")["price"].mean().sort_values(ascending=False).head(10)

product_category_name_english
computers                                1098.340542
small_appliances_home_oven_and_coffee     624.285658
home_appliances_2                         476.124958
agro_industry_and_commerce                342.124858
musical_instruments                       281.616000
small_appliances                          280.778468
fixed_telephony                           225.693182
construction_tools_safety                 208.992371
watches_gifts                             201.135984
air_conditioning                          185.269226
Name: price, dtype: float64

In [4]:
# 30.Top 10 product by Number of orders
b=order_items.groupby("product_id")["order_id"].count().sort_values(ascending=False).head(10)
b

product_id
aca2eb7d00ea1a7b8ebd4e68314663af    527
99a4788cb24856965c36a24e339b6058    488
422879e10f46682990de24d770e7f83d    484
389d119b48cf3043d311335e499d9c6b    392
368c6c730842d78016ad823897a372db    388
53759a2ecddad2bb87a079a1f1519f73    373
d1c427060a0f73f6b889a5c7c61f2ac4    343
53b36df67ebb7c41585e8d54d6772e08    323
154e7e31ebfa092203795c972e5804a6    281
3dd2a17168ec895c781a9191c1e95ad7    274
Name: order_id, dtype: int64

In [11]:
# 31.Bottom 10 Product Categories by Revenue.
a.groupby("product_category_name_english")["price"].sum().sort_values(ascending=True).head(10)

product_category_name_english
security_and_services         283.29
fashion_childrens_clothes     569.85
cds_dvds_musicals             730.00
home_comfort_2                760.27
flowers                      1110.04
diapers_and_hygiene          1567.59
arts_and_craftmanship        1814.01
la_cuisine                   2054.99
fashion_sport                2119.51
fashio_female_clothing       2803.64
Name: price, dtype: float64

### Payment Analysis

In [23]:
# 32.Payment Method with the Highest Total Payment Value
payments.groupby("payment_type")["payment_value"].sum().sort_values(ascending=False).head(10)

payment_type
credit_card    12542084.19
boleto          2869361.27
voucher          379436.87
debit_card       217989.79
not_defined           0.00
Name: payment_value, dtype: float64

In [24]:
# 33.Average Payment Value by Payment Method.
payments.groupby("payment_type")["payment_value"].mean().sort_values(ascending=False).head(10)

payment_type
credit_card    163.319021
boleto         145.034435
debit_card     142.570170
voucher         65.703354
not_defined      0.000000
Name: payment_value, dtype: float64

### Delivery & Review Analysis

In [38]:
# 34.Average Delivery Time By Customer State.
avg_delivery_time=orders.merge(customers[["customer_state","customer_id"]],on="customer_id")
avg_delivery_time.groupby("customer_state")["Delivery Days"].mean().sort_values(ascending=False)

customer_state
RR   29 days 09:18:03.975609
AP   27 days 04:26:29.850746
AM   26 days 10:13:25.613793
AL   24 days 13:03:09.103274
PA   23 days 18:33:00.021141
MA   21 days 13:45:05.167364
SE   21 days 12:28:29.707462
CE   21 days 06:23:52.394057
AC   21 days 00:51:25.600000
PB   20 days 10:14:32.721470
PI   19 days 10:58:13.289915
RO   19 days 08:55:43.954732
BA   19 days 08:03:04.247235
RN   19 days 06:40:32.696202
PE   18 days 10:45:35.106716
MT   18 days 01:20:17.319413
TO   17 days 15:47:36.609489
ES   15 days 18:56:36.134335
MS   15 days 14:50:22.763195
GO   15 days 14:33:07.649463
RJ   15 days 07:26:28.563263
RS   15 days 07:12:23.863023
SC   14 days 23:01:23.299971
DF   12 days 23:13:17.884615
MG   12 days 00:14:46.320827
PR   11 days 23:47:52.704448
SP    8 days 18:16:21.207111
Name: Delivery Days, dtype: timedelta64[us]

In [37]:
# 35.Relationship Between Review Score & Delivery Time.
r=orders.merge(reviews[["order_id","review_score"]],on="order_id")
r.groupby("review_score")["Delivery Days"].mean().sort_values(ascending=False)

review_score
1   21 days 07:28:26.611967
2   16 days 15:51:14.100306
3   14 days 06:17:13.556016
4   12 days 07:29:47.568125
5   10 days 16:31:35.505432
Name: Delivery Days, dtype: timedelta64[us]

In [17]:
# 36.Revenue by Customer State
a=customers.merge(orders[["order_id","customer_id"]],on="customer_id").merge(order_items[["order_id","price"]])
a.groupby("customer_state")["price"].sum().sort_values(ascending=False).head(10)

customer_state
SP    5202955.05
RJ    1824092.67
MG    1585308.03
RS     750304.02
PR     683083.76
SC     520553.34
BA     511349.99
DF     302603.94
GO     294591.95
ES     275037.31
Name: price, dtype: float64

In [22]:
# Top 10 Sellers By AOV (Average Order Value).
seller_aov=order_items.groupby("seller_id").agg(revenue=("price","sum"),orders=("order_id","nunique"))
seller_aov["AOV"]=seller_aov["revenue"]/seller_aov["orders"]
seller_aov.sort_values("AOV",ascending=False).head(10)

                                   revenue  orders          AOV
seller_id
80ceebb4ee9b31afb6c6a916a574a1e2   6729.00       1  6729.000000
ee27a8f15b1dded4d213a468ba4eb391   6499.00       1  6499.000000
b37c4c02bda3161a7546a4e6d222d5b2  24075.00       4  6018.750000
585175ec331ea177fa47199e39a6170a   3549.00       1  3549.000000
abe021b01ba992245271b9aa422032df   6720.00       2  3360.000000
a00824eb9093d40e589b940ec45c4eb0   9399.97       3  3133.323333
e2a1ac9bf33e5549a2a4f834e70df2f8  14999.45       5  2999.890000
e908c0f3646e8b60375734a350d95d71   2951.00       1  2951.000000
d63c73efd41eb002280e7ec831424edb   5598.00       2  2799.000000
1444c08e64d55fb3c25f0f09c07ffcf2   2749.00       1  2749.000000